### ISSUE TITLE
Axiom 3 doesn't work with 2 perpendicular lines

### ISSUE THREAD

**Issue by jgao222** [codeday-labs/three_folds#20]
title

**Comment by sstadnicki** [comment]
In fact, it doesn't even seem to work with non-perpendicular lines; the direction of the resulting crease is correct but its position isn't.

**Comment by jgao222** [comment]
There's a hack fix in #18 now to fix this, although it only works on the edges. It's just not a consistent fold operation, as there are always two choices, and it would be very hard to enforce the direction that every single line segment is created in.
